{{- if .Values.terraformHealth.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.terraformHealth.serviceAccountName }}
{{- if .Values.terraformHealth.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.terraformHealth.serviceAccountAnnotations | indent 4 }}
{{- end }}
{{- end }}
