{{- if .Values.terraformHealth.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: terraform-health
spec:
  runInterval: {{ .Values.terraformHealth.runInterval }}
  timeout: {{ .Values.terraformHealth.timeout }}
  podSpec:
    containers:
      - name: terraform-health
        image: {{ .Values.terraformHealth.image.repository }}:{{ .Values.terraformHealth.image.tag }}
        env:
        - name: GIT_USER
          value: {{ .Values.terraformHealth.git.username }}
        - name: GIT_URL
          value: {{ .Values.terraformHealth.git.url }}
        {{- range $pkey, $pval := .Values.terraformHealth.env }}
        - name: {{ $pkey }}
          value: {{ quote $pval }}
        {{- end }}
        {{- if .Values.terraformHealth.secretEnv }}
        envFrom:
          - secretRef:
              name: terraformdrift
        {{- end }}
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 40m
        restartPolicy: Never
    terminationGracePeriodSeconds: 60
    {{- if .Values.terraformHealth.serviceAccountName }}
    serviceAccountName: {{ .Values.terraformHealth.serviceAccountName  }}
    {{- end }}
{{- end }}
